version: "3.6"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always

volumes:
  mysql:
