version: "3.6"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'sf-forms'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always

volumes:
  mysql:
